### PR TITLE
Acknowledge prior art

### PR DESCRIPTION
**Pull request by johnsonr**
Make it clear that this is not a work of invention but articulation, to avoid misunderstanding our intent. People practice some or all of these techniques.

### CODE REVIEW

**Comment by jessitron** [comment]
How about we move it up one paragraph? I like the programming one last

**Comment by johnsonr** [comment]
@jessitron I agree. Please make the commit yourself, in the interests of transparency.

**Comment by johnsonr** [comment]
@jessitron can we also change "badly" to much when you make this extra commit, for a more positive wording.

**Review by jessitron — APPROVED** [review]

**Comment by cdupuis** [comment]
Pull request auto merged by Atomist.

* 1 approved review by @jessitron
* 1 successful check

[atomist:generated] [auto-merge:on-approve]

**Pull request merged**
